spring:
  application:
    name: service-registry

server:
  port: 8761
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:eureka.p12
    key-store-password: changeit
    key-alias: eureka
    trust-store: classpath:eureka.p12
    trust-store-password: changeit
  

  
  

eureka:
  instance:
    hostname: localhost
    port: ${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
